Pages/Aiuto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages.Shared
{
    public class AiutoModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPost(string email, string prob)
        {
            Program.email = email;
            Program.problema = prob;
            Program.SalvaProblema();
        }
    }
}

Pages/Bilancio.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class BilancioModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Bollettino.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class BollettinoModel : PageModel
    {
        public void OnGet()
        {
        }
        public void OnPostBollettino(string tipologia, string codice, string cc, double importo)
        {
            Program.tipologia = tipologia;
            Program.codice = codice;
            Program.cc = cc;
            Program.importo = importo;
            Program.EffettuaBollettino();
        }
    }
}

Pages/Bonifico.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class BonificoModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPostBonifico(string beneficiario, string IBAN, double importo, string data, string causale)
        {
            Program.utente = beneficiario;
            Program.IBAN = IBAN;
            Program.importo = importo;
            Program.data = data;
            Program.text = causale;
            Program.EffettuaBonifico();
        }
    }
}

Pages/Carta.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class CartaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Documenti.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class DocumentiModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyBank.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/IBAN.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class IBANModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBank.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Login.cshtml.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class LoginModel : PageModel
    {
        public int pnt;
        public void OnGet()
        {
        }

        public void OnPostLogin(string name, string email, string passwd)
        {
            Program.Search(ref email, ref passwd);
            if (email == Program.readerEmail[Program.pnt] && passwd == Program.readerPass[Program.pnt])
            {
                Startup.adminSetup = true;
                Program.LeggiUtente(ref name);
            }
            else if (email != Program.readerEmail[Program.pnt])
            {
                Startup.adminSetup = false;
                Program.error = "email";
            }   
            else
            {
                Startup.adminSetup = false;
                Program.error = "passwd";
            }
        }

        public void OnPostExit()
        {
            Startup.adminSetup = false;
        }
    }
}

Pages/Movimenti.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class MovimentiModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBank.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Profilo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class ProfiloModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPostNome(string utente)
        {
            Program.CambiaNome(ref utente);
        }

        public void OnPostPasswd(string passwd)
        {
            Program.CambiaPasswd(ref passwd);
        }
    }
}

Pages/Registrati.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class RegistratiModel : PageModel
    {
        public void OnGet()
        {
            
        }
        public void OnPostSignup(string name, string email, string passwd)
        {
            Program.Search(ref email, ref passwd);
            if (Program.exist == false) //se mail e password non compaiono nei file
            {
                Program.utente = name;
                Program.email = email;
                Program.passwd = passwd;
                Program.row++;
                Program.WriteFile();
                Program.ReadFile();
                Program.CreateFile(ref name, ref email, ref passwd);
            }
            else
                Program.error = "exist";
        }
    }
}

Pages/Ricarica.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyBank.Pages
{
    public class RicaricaModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPostRicarica(int importo)
        {
            Program.ricarica = importo;
        }
    }
}

Pages/Aiuto.cshtml
@page
@model MyBank.Pages.Shared.AiutoModel
@{
    ViewData["Title"] = "Aiuto";
}

<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row justify-content-center">
        <!--COLONNA DESTRA-->
        <div class="d-none d-sm-none d-md-none d-xl-block col-xl-3 order-xl-0">
            <div class="container" style="border-radius: 5px; margin-right: auto;">
                <br>
                Movimenti: per dare un occhio alle tue entrate e alle tue uscite recenti
                <hr>
                Bilancio: per avere una visione globale dell'andamento del tuo conto
                <hr>
                IBAN: per visualizzare le informazioni del tuo conto
                <hr>
                Bollettino: per pagare bollettini postali
                <hr>
                Bonifico: per effettuare bonifici verso altri clienti MyBank
                <hr>
                Ricarica: per ricaricare il saldo del tuo telefono
                <hr>
                Profilo: per gestire le tue informazioni personali
                <hr>
                Carta: per visualizzare le informazioni sulla tua carta MyBank
                <hr>
                Documenti: per caricare i tuoi file da scambiare con noi
                <br><br>
            </div>
        </div>

        <!--COLONNA CENTRALE-->
        <div class="col-lg-12 col-xl-6 order-lg-0 order-xl-1" id="centrale"><br>
            <form asp-page="/Aiuto" asp-page-handler="aiuto" class="form-signin" method="post">
                <div class="form-group">
                    <label for="InputEmail">Indirizzo email</label>
                    @{
                        if (Startup.adminSetup == false)
                        {
                            <input type="text" class="form-control" name="email" id="InputEmail" aria-describedby="emailHelp"
                                   placeholder="Enter Email">
                        }
                        else
                        {
                            <input type="text" readonly class="form-control" name="email" id="InputEmail" aria-describedby="emailHelp" placeholder="@Program.readerEmail[Program.pnt]">
                        }
                    }
                </div>
                <div class="form-group">
                    <label for="textArea">Descrivi il tuo problema</label>
                    <textarea class="form-control" id="textArea" rows="3" name="problem" placeholder="Indica il problema"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Invia</button><br>
            </form>
        </div>

        <!--COLONNA SINISTRA-->
        <div class="d-none d-sm-none d-xl-block col-xl-3 order-xl-2">
            <img src="~/images/superpubblicità.jpg" width="400" height="600" style="border-radius: 5px; margin-left: auto;">
        </div>
    </div>
</div>

Pages/Bilancio.cshtml
@page
@model MyBank.Pages.BilancioModel
@{
    ViewData["Title"] = "Bilancio";
}

<!--Intestazione-->
<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<!--Centrale-->
<div class="container" id="centrale">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <img src="~/images/bilancione.png" class="responsive" width="150" height="150" style="width: 100%; max-width: 150px; height: auto;">
            <br><br>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="d-none d-xl-block col-xl-5">
            <img src="~/images/frecciarossa.png" class="responsive" width="200" height="200">
            <br>
        </div>
        <div class="col-2"></div>
        <div class="d-none d-xl-block col-xl-5">
            <img src="~/images/frecciav.png" class="responsive" width="100" height="200">
            <br><br>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-5">
            <div class="alert alert-danger" role="alert">
                @Program.readerData[9];
            </div>
            <br><br><br>
        </div>
        <div class="col-2">
        </div>
        <div class="col-5">
            <div class="alert alert-success" role="alert">
                @Program.readerData[8];
            </div>
            <br><br><br>
        </div>
    </div>
</div>

Pages/Bollettino.cshtml
@page
@model MyBank.Pages.BollettinoModel
@{
    ViewData["Title"] = "Bollettino";
}

<!--Intestazione-->
<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<!--Centrale-->
<div class="container" id="centrale">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <img src="~/images/bollettone.png" class="responsive" width="250" height="200" style="width: 100%; max-width: 250px; height: auto;">
            <br><br>
            <form asp-page="/Bollettino" asp-page-handler="bollettino" class="form-signin" method="post">
                <div class="form-group">
                    <label for="tipo">Tipologia bollettino</label>
                    <input type="text" class="form-control" id="InputTipo" name="Tipologia" placeholder="Tipologia" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="codice">Codice a 18 cifre</label>
                    <input type="number" class="form-control" id="InputCodice" name="Codice" placeholder="Codice" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="conto">N. conto corrente</label>
                    <input type="number" class="form-control" id="InputConto" name="cc" placeholder="N. conto" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="importo">Importo del bollettino</label>
                    <input type="number" class="form-control" id="InputImporto" name="Importo" placeholder="Importo" aria-describedby="basic-addon1">
                </div>
                <button type="submit" class="btn btn-primary">Invia</button><br>
            </form>
            <br><br><br><br><br>
        </div>
    </div>
</div>

Pages/Bonifico.cshtml
@page
@model MyBank.Pages.BonificoModel
@{
    ViewData["Title"] = "Bonifico";
}

<!--Intestazione-->
<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<!--Centrale-->
<div class="container" id="centrale">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <img src="~/images/bank-draft.png" class="responsive" width="300" height="300" style="width: 100%; max-width: 300px; height: auto;">
            <form asp-page="/Bonifico" asp-page-handler="bonifico" class="form-signin" method="post">
                <div class="form-group">
                    <label for="InputUtente">Indica il beneficiario del bonifico</label>
                    <input type="text" class="form-control" id="InputBeneficiario" name="Beneficiario" placeholder="Beneficiario" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="InputIBAN">Specifica un IBAN</label>
                    <input type="text" class="form-control" id="InputIBAN" name="IBAN" placeholder="IBAN" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="InputImporto">Specifica un importo</label>
                    <input type="number" class="form-control" id="InputImporto" name="Importo" placeholder="Importo" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="InputData">Indica la data del bonifico</label>
                    <input type="text" class="form-control" id="InputData" name="Data" placeholder="Data" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="textArea">Indica una causale</label>
                    <textarea class="form-control" id="causale" rows="3" name="Causale" placeholder="Causale"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Invia</button><br>
            </form>
            <br><br><br><br><br>
        </div>
    </div>
</div>

Pages/Carta.cshtml
@page
@model MyBank.Pages.CartaModel
@{
    ViewData["Title"] = "Carta";
}

<!--Intestazione-->
<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<!--Centrale-->
<div class="container" id="centrale">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <img src="~/images/supercarta.png" class="responsive" width="325" height="200" style="width: 100%; max-width: 325px; height: auto;">
            <br><br>
            <form class="form-signin">
                <div class="form-group">
                    <label for="OutputUtente">Utente</label>
                    <input type="text" readonly class="form-control" value="@Program.readerData[0]" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="OutputNumero">Numero</label>
                    <input type="text" readonly class="form-control" value="@Program.readerData[3]" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="OutputPIN">PIN</label>
                    <input type="text" readonly class="form-control" value="@Program.readerData[4]" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="OutputCVV">CVV</label>
                    <input type="text" readonly class="form-control" value="@Program.readerData[5]" aria-describedby="basic-addon1">
                </div>
            </form>
            <br><br><br><br><br>
        </div>
    </div>
</div>

Pages/Login.cshtml
@page
@model MyBank.Pages.LoginModel
@{
    if (Startup.adminSetup == false)
        ViewData["Title"] = "Login";
    else
        ViewData["Title"] = "Esci";
}

<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row justify-content-center">
        <!--COLONNA DESTRA-->
        <div class="d-none d-sm-none d-md-none d-xl-block col-xl-3 order-xl-0">
            <div class="container" style="border-radius: 5px; margin-right: auto;">
                <br>
                Movimenti: per dare un occhio alle tue entrate e alle tue uscite recenti
                <hr>
                Bilancio: per avere una visione globale dell'andamento del tuo conto
                <hr>
                IBAN: per visualizzare le informazioni del tuo conto
                <hr>
                Bollettino: per pagare bollettini postali
                <hr>
                Bonifico: per effettuare bonifici verso altri clienti MyBank
                <hr>
                Ricarica: per ricaricare il saldo del tuo telefono
                <hr>
                Profilo: per gestire le tue informazioni personali
                <hr>
                Carta: per visualizzare le informazioni sulla tua carta MyBank
                <hr>
                Documenti: per caricare i tuoi file da scambiare con noi
                <br><br>
            </div>
        </div>

        <!--COLONNA CENTRALE-->
        <div class="col-lg-12 col-xl-6 order-lg-0 order-xl-1" id="centrale">
            @{
                if (Startup.adminSetup == false)
                {
                    <br>
                    <form asp-page="/Login" asp-page-handler="login" class="form-signin" method="post">
                        <div class="form-group">
                            <label for="InputName">Nome utente</label>
                            <input type="text" class="form-control" name="name" aria-describedby="emailHelp" placeholder="Enter Name">
                        </div>
                        <div class="form-group">
                            <label for="InputEmail">Indirizzo email</label>
                            <input type="text" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter Email">
                        </div>
                        <div class="form-group">
                            <label for="InputPassword">Password</label>
                            <input type="password" class="form-control" name="passwd" placeholder="Enter Password">
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                        <button type="submit" class="btn btn-primary" onclick="Adv()">Entra</button><br>
                    </form>
                }
                else
                {
                    <br>
                    <form asp-page="/Login" asp-page-handler="exit" class="form-signin" method="post">
                        <div class="form-group">
                            <label for="InputName">Nome utente</label>
                            <input type="text" readonly class="form-control" name="name" aria-describedby="emailHelp" value="@Program.readerName[Program.pnt]">
                        </div>
                        <div class="form-group">
                            <label for="InputEmail">Indirizzo email</label>
                            <input type="text" readonly class="form-control" name="email" aria-describedby="emailHelp" value="@Program.readerEmail[Program.pnt]">
                        </div>
                        <button type="submit" class="btn btn-primary">Esci</button><br>
                    </form>
                }
            }
        </div>

        <!--COLONNA SINISTRA-->
        <div class="d-none d-sm-none d-xl-block col-xl-3 order-xl-2">
            <img src="~/images/superpubblicità.jpg" width="400" height="600" style="border-radius: 5px; margin-left: auto;">
        </div>
    </div>
</div>

<script>
    function Adv()
    {
        switch (@Program.error)
        {
            case "email":
                alert("Indirizzo email errato");
                break;
            case "passwd":
                alert("Password errata");
                break;
            case "exist":
                alert("Utente già registrato");
                break;
            default:
                break;
        }
    }
</script>

Pages/Profilo.cshtml
@page
@model MyBank.Pages.ProfiloModel
@{
    ViewData["Title"] = "Profilo";
}

<!--Intestazione-->
<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<!--Centrale-->
<div class="container" id="centrale">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6" style="text-align: center;">
            <img src="~/images/profilone.png" class="responsive" width="200" height="200" style="width: 100%; max-width: 200px; height: auto;">
            <br><br>
                <form asp-page="/Profilo" asp-page-handler="nome" class="form-signin" method="post">
                    <div class="form-group">
                        <label for="utente">Indica un nuovo nome utente</label>
                        <input type="text" class="form-control" id="InputUtente" name="utente" placeholder="Nome utente" aria-describedby="basic-addon1">
                    </div>
                    <button type="submit" class="btn btn-primary">Cambia nome</button><br>
                </form><br><br>
                <form asp-page="/Profilo" asp-page-handler="passwd" class="form-signin" method="post">
                    <div class="form-group">
                        <label for="passwd">Indica una nuova password</label>
                        <input type="text" class="form-control" id="InputPasswd" name="passwd" placeholder="Password" aria-describedby="basic-addon1">
                    </div>
                    <button type="submit" class="btn btn-primary">Cambia password</button><br>
                </form>
            <br><br><br><br><br>
        </div>
    </div>
</div>

Pages/Registrati.cshtml
@page
@model MyBank.Pages.RegistratiModel
@{
    ViewData["Title"] = "Registrati";
}

<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <div class="col-6">
            <br><h2>@ViewData["Title"]</h2><br>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row justify-content-center">
        <!--COLONNA DESTRA-->
        <div class="d-none d-sm-none d-md-none d-xl-block col-xl-3 order-xl-0">
            <div class="container" style="border-radius: 5px; margin-right: auto;">
                <br>
                Movimenti: per dare un occhio alle tue entrate e alle tue uscite recenti
                <hr>
                Bilancio: per avere una visione globale dell'andamento del tuo conto
                <hr>
                IBAN: per visualizzare le informazioni del tuo conto
                <hr>
                Bollettino: per pagare bollettini postali
                <hr>
                Bonifico: per effettuare bonifici verso altri clienti MyBank
                <hr>
                Ricarica: per ricaricare il saldo del tuo telefono
                <hr>
                Profilo: per gestire le tue informazioni personali
                <hr>
                Carta: per visualizzare le informazioni sulla tua carta MyBank
                <hr>
                Documenti: per caricare i tuoi file da scambiare con noi
                <br><br>
            </div>
        </div>

        <!--COLONNA CENTRALE-->
        <div class="col-lg-12 col-xl-6 order-lg-0 order-xl-1" id="centrale">
            @{
                if (Startup.adminSetup == false)
                {
                    <br>
                    <form asp-page="/Registrati" asp-page-handler="signup" class="form-signin" method="post">
                        <div class="form-group">
                            <label for="InputnName">Nome e cognome</label>
                            <input type="text" class="form-control" name="name" id="InputName" aria-describedby="nameHelp" placeholder="Enter Name">
                        </div>
                        <div class="form-group">
                            <label for="InputEmail">Indirizzo email</label>
                            <input type="text" class="form-control" name="email" id="InputEmail" aria-describedby="emailHelp" placeholder="Enter Email">
                        </div>
                        <div class="form-group">
                            <label for="InputPassword">Password</label>
                            <input type="password" class="form-control" name="passwd" id="InputPasswd" placeholder="Enter Password">
                        </div>
                        <button type="submit" class="btn btn-primary" onclick="Adv()">Registrati</button><br>
                    </form>
                }
                else
                {
                    <br>
                    <form asp-page="/Registrati" asp-page-handler="signup" class="form-signin" method="post">
                        <div class="form-group">
                            <label for="InputnName">Nome e cognome</label>
                            <input type="text" readonly class="form-control" name="name" id="InputName" aria-describedby="nameHelp" value="@Program.readerName[Program.pnt]">
                        </div>
                        <div class="form-group">
                            <label for="InputEmail">Indirizzo email</label>
                            <input type="text" readonly class="form-control" name="email" id="InputEmail" aria-describedby="emailHelp" value="@Program.readerEmail[Program.pnt]">
                        </div>
                        <a href="/Login">Esci</a> per visualizzare i contenuti di questa pagina
                    </form>
                }
            }
        </div>

        <!--COLONNA SINISTRA-->
        <div class="d-none d-sm-none d-xl-block col-xl-3 order-xl-2">
            <img src="~/images/superpubblicità.jpg" width="400" height="600" style="border-radius: 5px; margin-left: auto;">
        </div>
    </div>
</div>

Pages/Ricarica.cshtml
@page
@model MyBank.Pages.RicaricaModel
@{
    ViewData["Title"] = "Ricarica";
}

<!--Intestazione-->
<div class="container" id="intestazione">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <br><h3>@ViewData["Title"]</h3><br>
        </div>
    </div>
</div>

<!--Centrale-->
<div class="container" id="centrale">
    <div class="row justify-content-center">
        <!--Colonna centrale-->
        <div class="col-6">
            <img src="~/images/Fulmine.png" class="responsive" width="250" height="250" style="width: 100%; max-width: 250px; height: auto;">
            <br><br>
            <form asp-page="/Ricarica" asp-page-handler="ricarica" class="form-signin" method="post">
                <div class="form-group">
                    <label for="InputTelefono">Indica un numero di telefono</label>
                    <input type="number" class="form-control" placeholder="Numero di telefono" aria-describedby="basic-addon1">
                </div>
                <div class="form-group">
                    <label for="InputImporto">Quanti soldi vuoi ricaricare?</label>
                    <input type="number" class="form-control" name="Importo" id="InputImporto" placeholder="Importo" aria-describedby="basic-addon1">
                </div>
                <button type="submit" class="btn btn-primary">Ricarica</button><br>
            </form>
            <br><br><br><br><br>
        </div>
    </div>
</div>